import { defineStore } from 'pinia'
import type IEditorStoreState from "@/interfaces/editorStoreState.ts";


export const useEditorStore = defineStore('editorStore', {
  state: (): IEditorStoreState => ({
    currentSection: "personal",
    formData: {
      full_name: "Karol Milewczyk",
      position_title: "Fullstack developer",
      email: "milewczyk@gmail.com",
      phone: "+48 510 695 802",
      location: "Bytów, PL",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",

      experience_formset: [
        {
          title: "Fullstack Developer",
          company: "Monser Inc.",
          start_date: "2025-01",
          end_date: "2025-12",
          is_ongoing: true,
          description: "Built and maintained full‑stack features using Vue, Quasar, TypeScript, and Node.js. Collaborated with designers and product managers to deliver high‑quality user experiences.",
        },
        {
          title: "Backend Developer",
          company: "Monser Inc.",
          start_date: "2024-01",
          end_date: "2024-12",
          is_ongoing: false,
          description: "Implemented REST APIs, optimized PostgreSQL queries, and introduced CI pipelines to improve deployment reliability.",
        },
        {
          title: "Frontend Developer",
          company: "Astera Labs",
          start_date: "2023-01",
          end_date: "2023-12",
          is_ongoing: false,
          description: "Migrated a legacy Vue 2 app to Vue 3 + Vite, improved Lighthouse scores by 25%.",
        },
        {
          title: "Software Engineer",
          company: "BluePeak",
          start_date: "2022-01",
          end_date: "2022-12",
          is_ongoing: false,
          description: "Delivered microservices in Node.js with robust monitoring and logging using OpenTelemetry.",
        },
        {
          title: "Junior Fullstack Developer",
          company: "CodeCraft",
          start_date: "2021-01",
          end_date: "2021-12",
          is_ongoing: false,
          description: "Built internal tools with Quasar Framework and Express.js, reducing manual work by 30%.",
        },
        {
          title: "Intern Software Engineer",
          company: "NovaSoft",
          start_date: "2020-07",
          end_date: "2020-12",
          is_ongoing: false,
          description: "Implemented unit tests and fixed bugs across the codebase; learned agile teamwork.",
        },
        {
          title: "Contract Developer",
          company: "Freelance",
          start_date: "2020-01",
          end_date: "2020-06",
          is_ongoing: false,
          description: "Delivered small business websites and dashboards using Vue and Firebase.",
        },
        {
          title: "Fullstack Developer",
          company: "HelixWorks",
          start_date: "2019-01",
          end_date: "2019-12",
          is_ongoing: false,
          description: "Introduced component libraries and storybook documentation to speed up development.",
        },
        {
          title: "Backend Engineer",
          company: "DataForge",
          start_date: "2018-01",
          end_date: "2018-12",
          is_ongoing: false,
          description: "Authored data processing pipelines and cron workers with Node and Redis.",
        },
        {
          title: "Web Developer",
          company: "BrightMedia",
          start_date: "2017-01",
          end_date: "2017-12",
          is_ongoing: false,
          description: "Built responsive UIs with Vue and SCSS; collaborated closely with marketing teams.",
        },
        {
          title: "Fullstack Engineer",
          company: "Quantum Apps",
          start_date: "2016-01",
          end_date: "2016-12",
          is_ongoing: false,
          description: "Designed RESTful services and integrated third‑party APIs (Stripe, Auth0).",
        },
        {
          title: "Software Engineer",
          company: "VectorX",
          start_date: "2015-01",
          end_date: "2015-12",
          is_ongoing: false,
          description: "Maintained legacy systems and gradually introduced TypeScript for safety.",
        },
        {
          title: "Junior Backend Developer",
          company: "NetPulse",
          start_date: "2014-01",
          end_date: "2014-12",
          is_ongoing: false,
          description: "Implemented background jobs and improved API response times by 15%.",
        },
        {
          title: "Support Developer",
          company: "TechAssist",
          start_date: "2013-01",
          end_date: "2013-12",
          is_ongoing: false,
          description: "Debugged production issues and wrote tooling to simplify support workflows.",
        },
        {
          title: "IT Assistant",
          company: "City Office",
          start_date: "2012-01",
          end_date: "2012-12",
          is_ongoing: false,
          description: "Helped with on‑prem systems and basic web page updates.",
        },
        {
          title: "Volunteer Developer",
          company: "OpenSource Org",
          start_date: "2011-01",
          end_date: "2011-12",
          is_ongoing: false,
          description: "Contributed documentation and minor bug fixes to open‑source projects.",
        },
        {
          title: "Intern Web Developer",
          company: "Startup Hub",
          start_date: "2010-07",
          end_date: "2010-12",
          is_ongoing: false,
          description: "Built simple landing pages; learned Git workflows and code reviews.",
        },
        {
          title: "Research Assistant",
          company: "Uni Labs",
          start_date: "2009-01",
          end_date: "2009-12",
          is_ongoing: false,
          description: "Assisted with data collection and analysis; scripted automation tasks.",
        },
        {
          title: "Teaching Assistant",
          company: "Community College",
          start_date: "2008-01",
          end_date: "2008-12",
          is_ongoing: false,
          description: "Helped students with introductory programming labs.",
        },
        {
          title: "Part‑time Web Developer",
          company: "Local Shop",
          start_date: "2007-01",
          end_date: "2007-12",
          is_ongoing: false,
          description: "Created a simple e‑commerce catalog and integrated payment links.",
        },
        {
          title: "Junior QA Engineer",
          company: "QualityWorks",
          start_date: "2006-01",
          end_date: "2006-12",
          is_ongoing: false,
          description: "Wrote test cases and assisted with regression testing; automated smoke tests.",
        },
        {
          title: "Apprentice Developer",
          company: "CraftWorks",
          start_date: "2005-01",
          end_date: "2005-12",
          is_ongoing: false,
          description: "Learned foundational web development skills and best practices.",
        }
      ],
      education_formset: [
        {
          title: "MSc Computer Science",
          school: "Gdańsk University of Technology",
          start_date: "2018-10",
          end_date: "2020-07",
          is_ongoing: false,
          description: "Specialized in distributed systems and software architecture. Thesis on event‑driven microservices.",
        },
        {
          title: "BSc Computer Science",
          school: "Gdańsk University of Technology",
          start_date: "2015-10",
          end_date: "2018-07",
          is_ongoing: false,
          description: "Coursework in algorithms, databases, and web development.",
        },
        {
          title: "Postgraduate Diploma – Data Engineering",
          school: "Warsaw School of Economics",
          start_date: "2021-10",
          end_date: "2022-07",
          is_ongoing: false,
          description: "Focused on data pipelines, warehousing, and analytics engineering.",
        },
        {
          title: "Certificate – Advanced TypeScript",
          school: "Online Academy",
          start_date: "2023-03",
          end_date: "2023-06",
          is_ongoing: false,
          description: "Covered generics, conditional types, and type‑safe API design.",
        },
        {
          title: "Certificate – Cloud Fundamentals",
          school: "CloudCert",
          start_date: "2022-03",
          end_date: "2022-05",
          is_ongoing: false,
          description: "Basics of AWS, IAM, networking, and serverless patterns.",
        },
        {
          title: "Nanodegree – Frontend Developer",
          school: "Udacity",
          start_date: "2019-05",
          end_date: "2019-10",
          is_ongoing: false,
          description: "Projects in responsive design, accessibility, and web performance.",
        },
        {
          title: "Course – Database Systems",
          school: "Open University",
          start_date: "2017-02",
          end_date: "2017-06",
          is_ongoing: false,
          description: "Relational modeling and SQL optimization techniques.",
        },
        {
          title: "Course – Algorithms and Data Structures",
          school: "Open University",
          start_date: "2016-02",
          end_date: "2016-06",
          is_ongoing: false,
          description: "Complexity analysis and practical data structure implementations.",
        },
        {
          title: "High School Diploma",
          school: "Bytów High School",
          start_date: "2011-09",
          end_date: "2014-05",
          is_ongoing: false,
          description: "Mathematics‑informatics profile; programming club member.",
        },
        {
          title: "Course – Reactive Programming",
          school: "Pluralsight",
          start_date: "2020-03",
          end_date: "2020-05",
          is_ongoing: false,
          description: "Streams, Observables, and state management with RxJS/Vue reactivity.",
        },
        {
          title: "Bootcamp – Fullstack Web Development",
          school: "CodeCamp",
          start_date: "2014-06",
          end_date: "2014-09",
          is_ongoing: false,
          description: "Intensive training in HTML/CSS/JS and backend fundamentals.",
        },
        {
          title: "Course – UX for Developers",
          school: "UX Academy",
          start_date: "2018-03",
          end_date: "2018-05",
          is_ongoing: false,
          description: "Usability heuristics, accessibility, and user research basics.",
        },
        {
          title: "Workshop – Kubernetes Basics",
          school: "Cloud Native Poland",
          start_date: "2021-04",
          end_date: "2021-04",
          is_ongoing: false,
          description: "Hands‑on intro to containers, pods, and services.",
        },
        {
          title: "Course – Advanced CSS",
          school: "Coursera",
          start_date: "2017-09",
          end_date: "2017-11",
          is_ongoing: false,
          description: "Grid, Flexbox, and performance best practices.",
        },
        {
          title: "Certificate – System Design",
          school: "Educative.io",
          start_date: "2022-08",
          end_date: "2022-10",
          is_ongoing: false,
          description: "Scalable systems, caching, and messaging patterns.",
        },
        {
          title: "Course – Testing JavaScript",
          school: "Testing Academy",
          start_date: "2020-08",
          end_date: "2020-10",
          is_ongoing: false,
          description: "Unit, integration, and E2E testing strategies.",
        },
        {
          title: "Course – Git & GitHub",
          school: "FreeCodeCamp",
          start_date: "2016-07",
          end_date: "2016-08",
          is_ongoing: false,
          description: "Version control workflows and collaboration.",
        },
        {
          title: "Certificate – Agile Fundamentals",
          school: "Scrum.org",
          start_date: "2019-02",
          end_date: "2019-03",
          is_ongoing: false,
          description: "Scrum roles, ceremonies, and artifacts in practice.",
        },
        {
          title: "Workshop – Docker Deep Dive",
          school: "DevOps Days",
          start_date: "2018-06",
          end_date: "2018-06",
          is_ongoing: false,
          description: "Containerization concepts and image optimization.",
        },
        {
          title: "Self‑Study – Algorithms",
          school: "Personal Project",
          start_date: "2015-01",
          end_date: "2015-12",
          is_ongoing: false,
          description: "Practiced algorithmic challenges and competitive programming.",
        },
        {
          title: "Course – Web Accessibility",
          school: "W3C",
          start_date: "2023-01",
          end_date: "2023-02",
          is_ongoing: false,
          description: "WCAG guidelines, ARIA roles, and inclusive design techniques.",
        }
      ],
      footer: "",
    },
  }),
  actions: {
    addNewForm(relatedSection: TSectionWithFormset): void {
      switch (relatedSection) {
        case "experience":
          this.formData.experience_formset.push({
            title: "",
            company: "",
            start_date: "",
            end_date: "",
            is_ongoing: false,
            description: "",
          });
          break;
        case "education":
          this.formData.education_formset.push({
            title: "",
            school: "",
            start_date: "",
            end_date: "",
            is_ongoing: false,
            description: "",
          });
          break;
      }
    },
    setCurrentSection(sectionName: TEditorSection): void {
      this.currentSection = sectionName;
    }
  },
  getters: {
    hasContactData(state): boolean {
      return state.formData.email.length + state.formData.phone.length + state.formData.location.length !== 0;
    },
  }
})
